Pinning npm to 1.3.14
1.3.15 causes nasty shit like this:

Running "prepare_install" task
Installing module

> heapdump@0.2.2 install /home/blalor/tmp/mk3test/RaceCaptureLive/target/package-root/opt/rclive/backend/lib/node_modules/rclive-backend/node_modules/heapdump
> node-gyp rebuild

Traceback (most recent call last):
  File "/home/blalor/tmp/mk3test/grunt-prepare-install/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
AttributeError: 'module' object has no attribute 'script_main'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/blalor/tmp/mk3test/grunt-prepare-install/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 2.6.32-279.el6.x86_64
gyp ERR! command "node" "/home/blalor/tmp/mk3test/grunt-prepare-install/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/blalor/tmp/mk3test/RaceCaptureLive/target/package-root/opt/rclive/backend/lib/node_modules/rclive-backend/node_modules/heapdump
gyp ERR! node -v v0.10.14
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/blalor/tmp/mk3test/RaceCaptureLive/target/package-root/opt/rclive/backend/lib/node_modules/rclive-backend/node_modules/zmq/test'
npm ERR! error rolling back  rclive-backend@3.0.1-alpha { [Error: ENOTEMPTY, rmdir '/home/blalor/tmp/mk3test/RaceCaptureLive/target/package-root/opt/rclive/backend/lib/node_modules/rclive-backend/node_modules/zmq/test']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/blalor/tmp/mk3test/RaceCaptureLive/target/package-root/opt/rclive/backend/lib/node_modules/rclive-backend/node_modules/zmq/test' }
ERROR
Warning: npm install failed: heapdump@0.2.2 install: `node-gyp rebuild`